openapi: 3.1.0
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  /v1/drinks/new:
    post:
      tags:
      - drinks-controller
      operationId: saveDrink
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Drink"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/SavedDrink"
  /v1/beer/{userId}/brands:
    post:
      tags:
      - beer-controller
      operationId: saveBrand
      parameters:
      - name: userId
        in: path
        required: true
        schema:
          type: string
          format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewBeerBrand"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Brand"
  /v1/beer/brands/{brandId}/flavours:
    get:
      tags:
      - beer-controller
      operationId: getBrandNames
      parameters:
      - name: brandId
        in: path
        required: true
        schema:
          type: integer
          format: int32
      - name: userId
        in: query
        required: true
        schema:
          type: string
          format: uuid
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/BeerFlavour"
    post:
      tags:
      - beer-controller
      operationId: saveBrandName
      parameters:
      - name: brandId
        in: path
        required: true
        schema:
          type: integer
          format: int32
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewBeerFlavour"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/BeerFlavour"
  /v1/alcohol/types:
    get:
      tags:
      - alcohol-controller
      operationId: getAlcoholTypes
      parameters:
      - name: userId
        in: query
        required: false
        schema:
          type: string
          format: uuid
          default: "10"
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/AlcoholType"
    post:
      tags:
      - alcohol-controller
      operationId: createAlcoholType
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewAlcoholEntry"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/AlcoholType"
  /v1/alcohol/types/{alcoholTypeId}/volumes:
    get:
      tags:
      - alcohol-controller
      operationId: getVolumesByAlcoholType
      parameters:
      - name: alcoholTypeId
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/AlcoholVolume"
    post:
      tags:
      - alcohol-controller
      operationId: saveVolumeForAlcoholType
      parameters:
      - name: alcoholTypeId
        in: path
        required: true
        schema:
          type: integer
          format: int32
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewVolumeEntry"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/AlcoholVolume"
  /v1/alcohol/types/{alcoholTypeId}/subtypes:
    get:
      tags:
      - alcohol-controller
      operationId: getSubtypesByAlcoholType
      parameters:
      - name: alcoholTypeId
        in: path
        required: true
        schema:
          type: integer
          format: int32
      - name: userId
        in: query
        required: true
        schema:
          type: string
          format: uuid
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/AlcoholSubtype"
    post:
      tags:
      - alcohol-controller
      operationId: getSubtypesByAlcoholType_1
      parameters:
      - name: alcoholTypeId
        in: path
        required: true
        schema:
          type: integer
          format: int32
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewAlcoholSubtype"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/AlcoholSubtype"
  /v1/recommendations/{userId}/list:
    get:
      tags:
      - recommendations-controller
      operationId: getRecommendationsList
      parameters:
      - name: userId
        in: path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Recommendation"
  /v1/beer/consumption-types:
    get:
      tags:
      - beer-controller
      operationId: getConsumptionTypesList
      parameters:
      - name: amount
        in: query
        required: false
        schema:
          type: integer
          format: int32
          default: 10
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ConsumptionType"
  /v1/beer/brands:
    get:
      tags:
      - beer-controller
      operationId: getBrandsList
      parameters:
      - name: userId
        in: query
        required: false
        schema:
          type: string
          format: uuid
          default: "10"
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Brand"
components:
  schemas:
    Drink:
      type: object
      properties:
        userId:
          type: string
          format: uuid
        date:
          type: string
        alcoholTypeId:
          type: integer
          format: int32
        alcoholSubtypeId:
          type: integer
          format: int32
        alcoholVolumeId:
          type: integer
          format: int32
        brandId:
          type: integer
          format: int32
        beerFlavourId:
          type: integer
          format: int32
        consumptionTypeId:
          type: integer
          format: int32
        comments:
          type: string
        quantity:
          type: integer
          format: int32
        addToRecommendations:
          type: boolean
        onlyTemporarily:
          type: boolean
        name:
          type: string
    SavedDrink:
      type: object
      properties:
        id:
          type: integer
          format: int32
        userId:
          type: string
          format: uuid
        date:
          type: string
        alcoholTypeId:
          type: integer
          format: int32
        alcoholSubtypeId:
          type: integer
          format: int32
        alcoholVolumeId:
          type: integer
          format: int32
        brandId:
          type: integer
          format: int32
        beerFlavourId:
          type: integer
          format: int32
        consumptionTypeId:
          type: integer
          format: int32
        comments:
          type: string
    NewBeerBrand:
      type: object
      properties:
        name:
          type: string
        flavours:
          type: array
          items:
            type: string
    Brand:
      type: object
      properties:
        id:
          type: integer
          format: int32
        userId:
          type: string
          format: uuid
        name:
          type: string
    NewBeerFlavour:
      type: object
      properties:
        userId:
          type: string
          format: uuid
        name:
          type: string
    BeerFlavour:
      type: object
      properties:
        id:
          type: integer
          format: int32
        brandId:
          type: integer
          format: int32
        userId:
          type: string
          format: uuid
        name:
          type: string
    NewAlcoholEntry:
      type: object
      properties:
        userId:
          type: string
          format: uuid
        name:
          type: string
        volumes:
          type: array
          items:
            $ref: "#/components/schemas/NewVolumeEntry"
        alcoholSubtypes:
          type: array
          items:
            type: string
    NewVolumeEntry:
      type: object
      properties:
        name:
          type: string
        volume:
          type: number
          format: float
    AlcoholType:
      type: object
      properties:
        id:
          type: integer
          format: int32
        userId:
          type: string
          format: uuid
        name:
          type: string
        volumeIds:
          type: array
          items:
            type: integer
            format: int32
    AlcoholVolume:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
        volume:
          type: number
          format: float
    NewAlcoholSubtype:
      type: object
      properties:
        alcoholTypeId:
          type: integer
          format: int32
        userId:
          type: string
          format: uuid
        name:
          type: string
    AlcoholSubtype:
      type: object
      properties:
        id:
          type: integer
          format: int64
        alcoholTypeId:
          type: integer
          format: int32
        userId:
          type: string
          format: uuid
        name:
          type: string
    Recommendation:
      type: object
      properties:
        id:
          type: integer
          format: int32
        userId:
          type: string
          format: uuid
        name:
          type: string
        alcoholTypeId:
          type: integer
          format: int32
        alcoholSubtypeId:
          type: integer
          format: int32
        alcoholVolumeId:
          type: integer
          format: int32
        brandId:
          type: integer
          format: int32
        beerFlavourId:
          type: integer
          format: int32
        consumptionTypeId:
          type: integer
          format: int32
        endDate:
          type: string
          format: date-time
    ConsumptionType:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
