apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "drinksaver-frontend.fullname" . }}-config
  labels:
    {{- include "drinksaver-frontend.labels" . | nindent 4 }}
data:
  VITE_API_URL: {{ .Values.backend.apiUrl | quote }}
